

#server port and Encoding
server:
  port: 9090
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
#  
#
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    url: jdbc:oracle:thin:@rclass.iptime.org:1521:xe
    username: eum
    password: eum1234@@
    
      


  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
        
      
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: idfordev12@gmail.com
    password: mxkxztagmrxckfzx
    properties:
      mail.smtp.auto: true
      mail.smtp.starttls.enable: true
 
#      
mybatis:
  mapper-locations: /mapper/**/*-mapper.xml
  
  configuration:
    map-underscore-to-camel-case: true
  
  
logging:
  level: 
    org.springframework.core: info
    org.springframework.beans: info
    org.springframework.context: info
    org.springframework.web: debug

   
  pattern:
    console: "%clr( %d{yyyy/MM/dd HH:mm} ){cyan} %clr(%-5p)  - %m%n"
    file: "%clr( %d{yyyy/MM/dd HH:mm} ){cyan} %clr(%-5p)  - %m%n"
   
    
  file:
    name: logs/eum.log
    max-history: 10
 
    
    
#    1. 로그 설정 이거 맞음?? 파일로 빼는데 rollingpolicy가 안먹음.
#    2. 인코딩
#    3. AOP
